services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: aspdb
      POSTGRES_USER: aspuser
      POSTGRES_PASSWORD: asppass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=aspdb;Username=aspuser;Password=asppass
    ports:
      - "5000:80"

volumes:
  pgdata:
